# Generated by Django 5.0.1 on 2024-03-01 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(blank=True, max_length=400, null=True, verbose_name='استان')),
                ('City', models.CharField(blank=True, max_length=400, null=True, verbose_name='شهر')),
                ('Neighbourhood', models.CharField(blank=True, max_length=400, null=True, verbose_name='محله')),
                ('Avenue', models.CharField(blank=True, max_length=400, null=True, verbose_name='خیابان')),
                ('Street', models.CharField(blank=True, max_length=400, null=True, verbose_name='کوچه')),
                ('Plaque', models.CharField(blank=True, max_length=400, null=True, verbose_name='پلاک')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_users', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
    ]
